[build]
rustflags = ["-Z", "threads=8"]

[unstable]
codegen-backend = true
[profile.dev]
codegen-backend = "cranelift"


[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/workspaces/mold/bin/mold"]
